### ISSUE TITLE
Can't launch the server

### ISSUE THREAD

**Issue by HaHaWTH** [embeddedt/Blacksmith#1]
I have built this javaagent just now, I tried to add it to my server launch argument, but it could not boot up
heres the argument: "..\jdk-8\bin\java.exe" -Xms64M -Xmx8G-javaagent:blacksmith-1.0-SNAPSHOT.jar -jar Server.jar --nogui
logs: 
[err.txt](https://github.com/embeddedt/Blacksmith/files/11712309/err.txt)

**Comment by embeddedt** [comment]
You need to build using the shadowJar task not the default build task. So
probably "gradlew shadowJar". The correct filename should then be
blacksmith-v1.jar
